name: tialink
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  dartz: ^0.10.1
  dio: ^5.2.1+1
  flutter_bloc: ^8.0.1
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^5.0.2

  # Bluetooth Classic library
  flutter_bluetooth_serial: ^0.4.0

  introduction_screen: ^3.0.0
  lottie: ^1.2.2
  get_it: ^7.2.0
  provider: ^6.0.2
  pinput: 2.1.4
  flutter_countdown_timer: ^4.1.0
  package_info_plus: ^1.4.0
  device_info_plus: ^3.2.2
  im_stepper: ^0.1.3
  tuple: ^2.0.0
  flutter_spinkit: ^5.1.0
  permission_handler: ^9.2.0
  flutter_svg: ^1.0.3
  animated_text_kit: ^4.2.1
  bloc_concurrency: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.5
  build_runner: ^2.1.7
  mockito: ^5.1.0
  http_mock_adapter: ^0.4.4
  test: ^1.22.0
  bloc_test: ^9.0.3
  faker: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/svg/
    - assets/images/
  fonts:
    - family: TiaLinkIcons
      fonts:
        - asset: assets/fonts/TiaLinkIcons.ttf