name: tialink
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  dartz: ^0.10.1
  dio: ^4.0.4
  flutter_bloc: ^8.0.1
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^5.0.2

  # Bluetooth Classic library
  flutter_bluetooth_serial: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.5
  build_runner: ^2.1.7
  mockito: ^5.1.0
  http_mock_adapter: ^0.3.2
  test: ^1.19.5
  bloc_test: ^9.0.3
  faker: ^2.0.0

flutter:
  uses-material-design: true
